[project]
name = "odoo-addons-sygel-technology-sy-partner-contact"
version = "17.0.20241120.0"
dependencies = [
    "odoo-addon-base_location_code_program_territory>=17.0dev,<17.1dev",
    "odoo-addon-partner_address_hide_pdf_fields>=17.0dev,<17.1dev",
    "odoo-addon-partner_code_program>=17.0dev,<17.1dev",
    "odoo-addon-partner_code_program_account>=17.0dev,<17.1dev",
    "odoo-addon-partner_code_program_hide_pdf_fields>=17.0dev,<17.1dev",
    "odoo-addon-partner_code_program_purchase>=17.0dev,<17.1dev",
    "odoo-addon-partner_code_program_sale>=17.0dev,<17.1dev",
    "odoo-addon-partner_code_program_territory>=17.0dev,<17.1dev",
    "odoo-addon-partner_code_program_territory_account>=17.0dev,<17.1dev",
    "odoo-addon-partner_code_program_territory_hide_pdf_fields>=17.0dev,<17.1dev",
    "odoo-addon-partner_code_program_territory_purchase>=17.0dev,<17.1dev",
    "odoo-addon-partner_code_program_territory_sale>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_old_acc_number>=17.0dev,<17.1dev",
    "odoo-addon-partner_contact_old_migration_fields>=17.0dev,<17.1dev",
    "odoo-addon-partner_disable_vat_verification>=17.0dev,<17.1dev",
    "odoo-addon-partner_industrial_estate>=17.0dev,<17.1dev",
    "odoo-addon-partner_industrial_estate_hide_pdf_fields>=17.0dev,<17.1dev",
    "odoo-addon-partner_private_information>=17.0dev,<17.1dev",
    "odoo-addon-partner_private_information_autocomplete>=17.0dev,<17.1dev",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 17.0",
]
