[project]
name = "odoo-addons-sygel-technology-sy-partner-contact"
version = "18.0.20250702.2"
dependencies = [
    "odoo-addon-base_location_code_program_territory==18.0.*",
    "odoo-addon-partner_code_program==18.0.*",
    "odoo-addon-partner_code_program_account==18.0.*",
    "odoo-addon-partner_code_program_purchase==18.0.*",
    "odoo-addon-partner_code_program_sale==18.0.*",
    "odoo-addon-partner_code_program_territory==18.0.*",
    "odoo-addon-partner_code_program_territory_sale==18.0.*",
    "odoo-addon-partner_industrial_estate==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
